<script setup>
import { ref } from 'vue';
import { Link, router, usePage } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';
import CalendarEventEditor from '@/Components/Work/CalendarEventEditor.vue';
import PageLinks from '@/Components/Work/PageLinks.vue';
defineOptions({ layout: AppLayout });
const props = defineProps({ events: Object, changes: Object, calendars: Array, connection: Object, date: String, minDate: String, maxDate: String, timezone: String, requestKey: String });
const editing = ref(null);
const busy = ref(false);
const page = usePage();
const dateLabel = value => new Intl.DateTimeFormat('en-US', {month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:props.timezone}).format(new Date(value));
const act = (change, action) => router.post(route(`calendar.changes.${action}`, change.id), {}, { preserveScroll: true, onStart: () => {busy.value = true;}, onFinish: () => {busy.value = false;} });
</script>
<template>
    <div class="mb-7 flex flex-wrap items-center justify-between gap-3"><div><p class="work-eyebrow">Time ahead</p><h2 class="work-heading">Calendar</h2></div><Link :href="route('calendar.settings')" class="btn btn-ghost text-primary">Calendar settings →</Link></div>
    <p v-for="(error, key) in page.props.errors" :key="key" role="alert" class="mb-3 text-sm text-error">{{ error }}</p>
    <p v-if="!connection || connection.status !== 'connected'" class="mb-5 rounded-xl bg-warning/10 p-4 text-sm">{{ connection?.status === 'reauth_required' ? 'Reconnect Google to resume syncing. Saved calendar data may be out of date.' : 'Connect Google and select calendars in Calendar settings.' }}</p>
    <p v-for="calendar in calendars.filter(c => c.error)" :key="calendar.id" class="mb-3 text-sm text-warning">{{ calendar.name }}: {{ calendar.error }}</p>
    <div class="mb-5 flex flex-wrap items-end justify-between gap-3"><label class="min-w-0 text-sm">Week starting<input :value="date" :min="minDate" :max="maxDate" type="date" class="input mt-1 block w-full min-w-0" @change="router.get(route('calendar.index'), { date: $event.target.value })" /></label><button v-if="connection?.status === 'connected' && calendars.some(c => c.mode === 'two_way')" class="btn btn-primary" @click="editing = {}">New event</button></div>
    <p class="mb-5 text-xs text-base-content/55">{{ timezone }} · Recurring occurrences are available for the coming 90 days. <a href="https://calendar.google.com/calendar/" target="_blank" rel="noopener noreferrer" class="text-primary underline">Open Google Calendar</a></p>
    <CalendarEventEditor v-if="editing" :key="editing.id || 'new'" :event="editing" :calendars="calendars" :timezone="timezone" :request-key="requestKey" @close="editing = null" />
    <section class="space-y-3"><article v-for="event in events.data" :key="event.id" class="rounded-xl border border-base-300 bg-base-100 p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="break-words font-medium">{{ event.title }}</h3><p class="mt-1 text-sm text-base-content/65">{{ event.all_day ? `${event.start_date} · all day${event.last_day !== event.start_date ? ` through ${event.last_day}` : ''}` : `${dateLabel(event.starts_at)} – ${dateLabel(event.ends_at)}` }}</p><p class="mt-2 text-xs text-base-content/55">{{ event.calendar.name }}{{ event.recurring_event_id ? ' · recurring occurrence' : '' }}{{ !event.etag ? ' · waiting for Google' : '' }}</p><p v-if="event.location" class="mt-2 break-words text-sm">{{ event.location }}</p></div><button v-if="event.editable && event.calendar.mode === 'two_way' && connection?.status === 'connected'" class="btn btn-ghost btn-sm min-h-11 shrink-0" :aria-label="`Edit ${event.title}`" @click="editing = event">Edit</button></div></article><p v-if="!events.data.length" class="rounded-xl border border-dashed border-base-300 p-5 text-sm text-base-content/55">No synced events in this week.</p><PageLinks :page="events" /></section>
    <section class="mt-8"><h3 class="mb-4 font-semibold">Saved changes</h3><p v-if="!changes.data.length" class="text-sm text-base-content/55">No event changes saved from Chart yet.</p><article v-for="change in changes.data" :key="change.id" class="mb-3 rounded-xl border border-base-300 bg-base-100 p-4"><p class="break-words text-sm font-medium">{{ change.payload.summary || 'Undo event creation' }}</p><p class="mt-1 text-xs text-base-content/65">{{ change.undo_of_id ? 'Undo · ' : '' }}{{ change.status === 'applied' ? 'Confirmed by Google' : change.status === 'pending' ? 'Waiting for Google confirmation' : change.status }}</p><p v-if="change.error" class="mt-2 text-sm text-warning">{{ change.error }}</p><div class="mt-2 flex flex-wrap gap-2"><button v-if="['pending', 'failed', 'conflict'].includes(change.status) && (!change.attempts || change.status === 'conflict')" class="btn btn-ghost btn-sm min-h-11" :disabled="busy" @click="act(change, 'discard')">Discard saved change</button><button v-if="change.status === 'failed'" class="btn btn-ghost btn-sm min-h-11" :disabled="busy" @click="act(change, 'retry')">Retry</button><button v-if="change.status === 'applied' && !change.undo_of_id && change.operation !== 'delete'" class="btn btn-ghost btn-sm min-h-11" :disabled="busy" @click="act(change, 'undo')">Undo</button></div><p v-if="change.status === 'conflict'" class="mt-2 text-xs text-base-content/55">Google’s version has been kept. Discard this proposal, then edit the current event to make a new change.</p></article><PageLinks :links="changes.links" /></section>
</template>
