<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CaptureController;
use App\Http\Controllers\CaptureTokenController;
use App\Http\Controllers\DailyPlanController;
use App\Http\Controllers\DataExportController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\NotificationFeedController;
use App\Http\Controllers\ObservationController;
use App\Http\Controllers\ParserPreviewController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PushSubscriptionController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\WorkController;
use App\Http\Controllers\WorkWaitController;
use App\Http\Middleware\RequireTwoFactorAuthentication;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function (Request $request) {
    return $request->user() ? redirect()->route('dashboard') : Inertia::render('Home');
})->name('home');

Route::get('/up', fn () => response()->json(['status' => 'ok']))->name('health');

Route::middleware(['auth', config('jetstream.auth_session'), RequireTwoFactorAuthentication::class])
    ->group(function () {
        Route::get('/settings/export', DataExportController::class)->middleware('throttle:2,1,data-export')->name('work.export');
        Route::get('/settings/notifications', [PushSubscriptionController::class, 'index'])->name('push.settings');
        Route::post('/settings/notifications/subscriptions', [PushSubscriptionController::class, 'store'])->middleware('throttle:10,1,push-store')->name('push.store');
        Route::delete('/settings/notifications/subscriptions/{subscription}', [PushSubscriptionController::class, 'destroy'])->name('push.destroy');
        Route::post('/settings/notifications/subscriptions/{subscription}/test', [PushSubscriptionController::class, 'test'])->middleware('throttle:3,1,push-test')->name('push.test');
        Route::get('/settings/calendar', [CalendarController::class, 'settings'])->name('calendar.settings');
        Route::post('/settings/calendar/connect', [CalendarController::class, 'connect'])->middleware('throttle:5,1')->name('calendar.connect');
        Route::get('/settings/calendar/callback', [CalendarController::class, 'callback'])->name('calendar.callback');
        Route::post('/settings/calendar/refresh', [CalendarController::class, 'refresh'])->middleware('throttle:5,1')->name('calendar.refresh');
        Route::delete('/settings/calendar/connection', [CalendarController::class, 'disconnect'])->name('calendar.disconnect');
        Route::put('/settings/calendar/{calendar}', [CalendarController::class, 'selection'])->name('calendar.selection');
        Route::get('/calendar', [CalendarController::class, 'index'])->name('calendar.index');
        Route::post('/calendar/events', [CalendarController::class, 'store'])->name('calendar.events.store');
        Route::put('/calendar/events/{event}', [CalendarController::class, 'update'])->name('calendar.events.update');
        Route::post('/calendar/changes/{mutation}/discard', [CalendarController::class, 'discard'])->name('calendar.changes.discard');
        Route::post('/calendar/changes/{mutation}/retry', [CalendarController::class, 'retry'])->name('calendar.changes.retry');
        Route::post('/calendar/changes/{mutation}/undo', [CalendarController::class, 'undo'])->name('calendar.changes.undo');
        Route::get('/dashboard', [WorkController::class, 'dashboard'])->name('dashboard');
        Route::get('/daily-plan/tasks', [DailyPlanController::class, 'tasks'])->name('daily-plan.tasks');
        Route::put('/daily-plan', [DailyPlanController::class, 'update'])->name('daily-plan.update');
        Route::get('/bench', [WorkController::class, 'bench'])->name('bench');
        Route::get('/activity', [ActivityController::class, 'index'])->name('activity.index');
        Route::post('/activity', [ActivityController::class, 'store'])->name('activity.store');
        Route::put('/activity/{activity}', [ActivityController::class, 'update'])->name('activity.update');
        Route::delete('/activity/{activity}', [ActivityController::class, 'destroy'])->name('activity.destroy');
        Route::get('/intake', [WorkController::class, 'intake'])->name('intake');
        Route::get('/observations', [ObservationController::class, 'index'])->name('observations.index');
        Route::patch('/observations/{observation}', [ObservationController::class, 'update'])->name('observations.update');
        Route::get('/notifications', [NotificationFeedController::class, 'index'])->name('notifications.index');
        Route::post('/notifications/read-all', [NotificationFeedController::class, 'readAll'])->name('notifications.read-all');
        Route::patch('/notifications/{notification}', [NotificationFeedController::class, 'update'])->name('notifications.update');
        Route::post('/captures', [CaptureController::class, 'store'])->middleware('throttle:30,1')->name('captures.store');
        Route::get('/captures/{capture}', [CaptureController::class, 'show'])->name('captures.show');
        Route::post('/captures/{capture}/retry', [CaptureController::class, 'retry'])->middleware('throttle:10,1')->name('captures.retry');
        Route::put('/capture-items/{item}', [CaptureController::class, 'resolve'])->name('capture-items.resolve');
        Route::post('/capture-items/{item}/retry', [CaptureController::class, 'retryItem'])->name('capture-items.retry');
        Route::post('/capture-items/{item}/undo', [CaptureController::class, 'undo'])->name('capture-items.undo');
        Route::get('/ideas', [WorkController::class, 'ideas'])->name('ideas');
        Route::get('/more', fn () => Inertia::render('Work/More'))->name('more');
        Route::get('/settings/work', [WorkController::class, 'settings'])->name('work.settings');
        Route::post('/settings/capture-tokens', [CaptureTokenController::class, 'store'])->middleware('throttle:5,1')->name('capture-tokens.store');
        Route::delete('/settings/capture-tokens/{token}', [CaptureTokenController::class, 'destroy'])->name('capture-tokens.destroy');
        Route::post('/settings/parser/preview', ParserPreviewController::class)->middleware('throttle:5,1')->name('parser.preview');
        Route::put('/settings/timezone', [WorkController::class, 'timezone'])->name('work.timezone');
        Route::post('/domains', [DomainController::class, 'store'])->name('domains.store');
        Route::put('/domains/{domain}', [DomainController::class, 'update'])->name('domains.update');
        Route::delete('/domains/{domain}', [DomainController::class, 'destroy'])->name('domains.destroy');
        Route::post('/projects', [ProjectController::class, 'store'])->name('projects.store');
        Route::get('/projects/{project}', [WorkController::class, 'project'])->name('projects.show');
        Route::put('/projects/{project}', [ProjectController::class, 'update'])->name('projects.update');
        Route::patch('/projects/{project}/waiting', [WorkWaitController::class, 'project'])->name('projects.waiting');
        Route::delete('/projects/{project}', [ProjectController::class, 'destroy'])->name('projects.destroy');
        Route::post('/projects/{project}/restore', [ProjectController::class, 'restore'])->name('projects.restore');
        Route::get('/tasks/{task}', [TaskController::class, 'show'])->name('tasks.show');
        Route::post('/projects/{project}/milestones', [MilestoneController::class, 'store'])->name('milestones.store');
        Route::put('/projects/{project}/milestones/{milestone}', [MilestoneController::class, 'update'])->name('milestones.update');
        Route::delete('/projects/{project}/milestones/{milestone}', [MilestoneController::class, 'destroy'])->name('milestones.destroy');
        Route::post('/tasks', [TaskController::class, 'store'])->name('tasks.store');
        Route::put('/tasks/{task}', [TaskController::class, 'update'])->name('tasks.update');
        Route::patch('/tasks/{task}/waiting', [WorkWaitController::class, 'task'])->name('tasks.waiting');
        Route::patch('/tasks/{task}/completion', [TaskController::class, 'completion'])->name('tasks.completion');
        Route::delete('/tasks/{task}', [TaskController::class, 'destroy'])->name('tasks.destroy');
        Route::post('/tasks/{task}/restore', [TaskController::class, 'restore'])->name('tasks.restore');
        Route::post('/ideas', [IdeaController::class, 'store'])->name('ideas.store');
        Route::put('/ideas/{idea}', [IdeaController::class, 'update'])->name('ideas.update');
        Route::patch('/ideas/{idea}/review', [IdeaController::class, 'review'])->name('ideas.review');
    });

require __DIR__.'/jetstream.php';
